services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      VUE_APP_API_URL: http://backend:8080
    container_name: taskmaster-frontend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      - db
    container_name: taskmaster-backend
    networks:
      - app-network
  
  db:
    image: postgres:17-alpine
    restart: always
    ports:
      - "127.0.0.1:5432:5432"  # 127.0.0.1:5432:5432
    env_file:
      - ./.env
    volumes:
      - taskmaster_v2_db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: taskmaster-db
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge
  
volumes:
  taskmaster_v2_db_data: